version: "2.0"

services:
  pelican:
    container_name: pelican
    image: alexandreoda/pelican
    restart: unless-stopped
    privileged: true
    volumes:
      - "${HOME}:/home/pelican"
      - "$(pwd):/srv/pelican"
    ports:
      - "8000"